### ISSUE TITLE
Failed to downmix 5.1 channels audio to 2 channel for xbox360 profile

### ISSUE THREAD

**Issue by whoelse** [jbillo/xenonmkv#1]
Firstly, thank you for the great script.

I think I found a bug in the audio channel downmix code.  I don't know python, but I had to change line 255 in xenonmkv.py

if int(track.channels) <= int(args.channels):

Because the comparison failed to spot that 5.1 channels is greater than 2.

Regards

Chris

**Comment by jbillo** [comment]
Thanks for the report. I'll see if I can fix this in the development branch
this evening. I think I see the issue - args.channels from the command line
is considered a string, and track.channels should always be an int from
line 248. You're correct that both should be ints for comparison.

Out of curiosity, what does 'mediainfo' report for the number of channels
in the audio track in your file, so I can check all the conditions around
this?

Thanks,

Jake

**Comment by whoelse** [comment]
Hi Jake

Pleased I could help.  mediainfo reports 6 channels.

Audio
ID                                       : 2
Format                                   : AAC
Format/Info                              : Advanced Audio Codec
Format profile                           : LC
Codec ID                                 : A_AAC
Duration                                 : 2h 20mn
Channel(s)                               : 6 channels
Channel positions                        : Front: L C R, Side: L R, LFE
Sampling rate                            : 48.0 KHz
Compression mode                         : Lossy
Language                                 : English
Default                                  : Yes
Forced                                   : No

**Comment by jbillo** [comment]
Thanks. The version in the development branch at https://github.com/jbillo/xenonmkv/tree/development should now have a fix to cast the args.channels property as an int and therefore compare the correct value for audio downmixing. I will publish to the master branch after a few more testcases are written and available, but the development version as of now should be usable.

**Comment by jbillo** [comment]
Master branch updated to include this fix. Thanks again!
