### ISSUE TITLE
Hooks for GUI

### ISSUE THREAD

**Issue by ghost** [jbillo/xenonmkv#12]
Hey, I'm interested in writing a simple GUI for this script. What do you think the major problems would be - are there any obvious points to 'hook' the script?

**Comment by jbillo** [comment]
Hey,

I think the major concern would be parsing and displaying progress output from each of the tools. Apart from that, pretty much all a GUI would need to do is call the main application with the appropriate flags for video input and remuxing parameters. 

The last version of this utility was able to do a rudimentary progress bar based on percentages, but it might just be easiest to display stdout/stderr in a scrolling console window (at least initially).
